version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mam-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: helloMam
    ports:
      - "3308:3306"

  mongo-db:
    image: mongo:6.0
    container_name: grandma-mongo
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_DATABASE: helloGrandma
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password

  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - "6379:6379"

  hello-mam:
    depends_on:
      - mysql-db
      - redis
    build: ./Hello-Mam
    container_name: hello-mam
    restart: on-failure
    ports:
      - "8082:8080"

  hello-grandma:
    depends_on:
      - mongo-db
    build: ./hello-grandma
    container_name: hello-grandma
    ports:
      - "8080:8080"