version: '3'

services:
  mysql-db:
    image: mysql
    container_name: mam-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: helloMam
      MYSQL_ROOT_PASSWORD: secret

  mongo-db:
    image: mongo
    container_name: grandma-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: helloGrandma
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  hello-mam:
    build: ./Hello-Mam
    container_name: hello-mam
    ports:
      - "8080:8080"

  hello-grandma:
    build: ./hello-grandma
    container_name: hello-grandma
    ports:
      - "8082:8080"