#docker-compose up -d --force-recreate
version: '3'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mam-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: helloMam
      MYSQL_ROOT_PASSWORD: secret

  mongo-db:
    image: mongo:6.0
    container_name: grandma-mongo
    ports:
      - "27017:27017"
    environment:
        MONGO_INITDB_DATABASE: helloGrandma
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: password

  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - "6379:6379"

  hello-mam:
    build: ./Hello-Mam
    container_name: hello-mam
    ports:
      - "8080:8080"

  hello-grandma:
    build: ./hello-grandma
    container_name: hello-grandma
    ports:
      - "8082:8080"